### ISSUE TITLE
Pretty print

### ISSUE THREAD

**Issue by svnpenn** [tidwall/jsoned#3]
Using this file:

~~~
$ cat x.json
{"name":{"first":"Tom","last":"Smith"}}
~~~

JQ can pretty print a block:

~~~
$ jq .name x.json
{
  "first": "Tom",
  "last": "Smith"
}
~~~

JSONed seems to have no way to do that:

~~~
$ jsoned -i x.json name
{"first":"Tom","last":"Smith"}
~~~

**Comment by svnpenn** [comment]
https://github.com/tidwall/jsoned/issues/4

**Comment by tidwall** [comment]
I just added a -p flag that will now pretty print. Also the keypath is optional when the -p flag is specified.

**Comment by svnpenn** [comment]
confirmed fixed - damn that was fast - thanks

**Comment by tidwall** [comment]
Thanks! I'll close these issues. Feel free to reopen if you run into any problems.
