### ISSUE TITLE
Root object

### ISSUE THREAD

**Issue by svnpenn** [tidwall/jsoned#4]
Using this file:

~~~
$ cat z.json
{"name":{"first":"Tom","last":"Smith"}}
~~~

JQ can get the root object, AKA the whole file:

~~~
$ jq . z.json
{
  "name": {
    "first": "Tom",
    "last": "Smith"
  }
}
~~~

JSONed can get a block, but seems to have no way to get the whole file:

~~~
$ jsoned -i z.json name
{"first":"Tom","last":"Smith"}
~~~

Granted, this might only be useful when combined with pretty printing, otherwise
output is identical to cat.

**Comment by svnpenn** [comment]
https://github.com/tidwall/jsoned/issues/3

**Comment by svnpenn** [comment]
This is a workaround, but will fail if key exists:

~~~
$ jsoned -i z.json -D 0
{"name":{"first":"Tom","last":"Smith"}}
~~~

**Comment by tidwall** [comment]
With the new release from a few minutes ago you can now:
```
jsoned $ jsoned -i z.json -p
{
  "name": {
    "first": "Tom",
    "last": "Smith"
  }
}
```

**Comment by svnpenn** [comment]
confirmed fixed - damn that was fast - thanks
